version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-dbup-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
            - run: chmod +x cloud_sql_proxy
            - run: touch ./gcloud_service_key && echo "${GCLOUD_SERVICE_KEY}" > ./gcloud_service_key
            - run: 
              command: ./cloud_sql_proxy -instances=cookbook-274401:us-east1:cookbook-sql=tcp:5432 -credential_file=./gcloud_service_key
              background: true
            - run: cd cookbook-api
            - run: npm install
            - run: npm run dbup
          
workflows:
    build-dbup-test:
      jobs:
        - build-dbup-test