version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-dbup-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd cookbook-api
            - run: npm install
            - run: npm run dbup
workflows:
    build-dbup-test:
      jobs:
        - build-dbup-test