version: 2.1
jobs:
  build-dbup-test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
      - run: chmod +x cloud_sql_proxy
      - run: touch ./gcloud_service_key && echo "${GCLOUD_SERVICE_KEY}" > ./gcloud_service_key
      - run: 
          name: start proxy
          command: ./cloud_sql_proxy -instances=cookbook-274401:us-east1:cookbook-sql=tcp:5432 -credential_file=./gcloud_service_key
          background: true
      - run: cd cookbook-api && npm install && npm run dbup
          
workflows:
    build-dbup-test:
      jobs:
        - build-dbup-test
            filters:
              branches:
                only:
                  - master
